<?php

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class BuseSeeder extends Seeder
{
    public function run()
    {
        DB::table('buse')->insert([
            [
                'route_id' => 2,
                'driver_id' => 3,
                'coach_id' => 6,
                'start_day' => '2018-10-25',
                'start_time' => '22:00:00',
                'is_active' => 1,
                'price' => 340000,
                'number_seat' => '33',
                'user_add_id' => null,
            ],
            [
                'route_id' => 4,
                'driver_id' => 4,
                'coach_id' => 6,
                'start_day' => '2018-10-25',
                'start_time' => '07:30:00',
                'is_active' => 2,
                'price' => 220000,
                'number_seat' => '35',
                'user_add_id' => null,
            ],
            [
                'route_id' => 3,
                'driver_id' => 3,
                'coach_id' => 6,
                'start_day' => '2018-10-25',
                'start_time' => '08:30:00',
                'is_active' => 1,
                'price' => 220000,
                'number_seat' => '38',
                'user_add_id' => null,
            ],
            [
                'route_id' => 6,
                'driver_id' => 3,
                'coach_id' => 6,
                'start_day' => '2018-10-25',
                'start_time' => '09:30:00',
                'is_active' => 1,
                'price' => 220000,
                'number_seat' => '45',
                'user_add_id' => null,
            ],
            [
                'route_id' => 6,
                'driver_id' => 3,
                'coach_id' => 6,
                'start_day' => '2018-10-25',
                'start_time' => '10:30:00',
                'is_active' => 2,
                'price' => 220000,
                'number_seat' => '45',
                'user_add_id' => null,
            ],
            [
                'route_id' => 6,
                'driver_id' => 3,
                'coach_id' => 6,
                'start_day' => '2018-10-25',
                'start_time' => '19:30:00',
                'is_active' => 3,
                'price' => 220000,
                'number_seat' => '45',
                'user_add_id' => null,
            ],
            [
                'route_id' => 6,
                'driver_id' => 4,
                'coach_id' => 6,
                'start_day' => '2018-10-25',
                'start_time' => '21:30:00',
                'is_active' => 2,
                'price' => 220000,
                'number_seat' => '45',
                'user_add_id' => null,
            ],
            [
                'route_id' => 6,
                'driver_id' => 4,
                'coach_id' => 6,
                'start_day' => '2018-10-25',
                'start_time' => '23:30:00',
                'is_active' => 1,
                'price' => 220000,
                'number_seat' => '45',
                'user_add_id' => null,
            ],
            [
                'route_id' => 6,
                'driver_id' => 3,
                'coach_id' => 6,
                'start_day' => '2018-10-25',
                'start_time' => '22:30:00',
                'is_active' => 2,
                'price' => 220000,
                'number_seat' => '45',
                'user_add_id' => null,
            ],
            [
                'route_id' => 6,
                'driver_id' => 4,
                'coach_id' => 6,
                'start_day' => '2018-10-26',
                'start_time' => '07:30:00',
                'is_active' => 1,
                'price' => 220000,
                'number_seat' => '45',
                'user_add_id' => null,
            ],
            [
                'route_id' => 6,
                'driver_id' => 4,
                'coach_id' => 6,
                'start_day' => '2018-10-26',
                'start_time' => '08:30:00',
                'is_active' => 2,
                'price' => 220000,
                'number_seat' => '45',
                'user_add_id' => null,
            ],
            [
                'route_id' => 6,
                'driver_id' => 4,
                'coach_id' => 6,
                'start_day' => '2018-10-26',
                'start_time' => '09:30:00',
                'is_active' => 1,
                'price' => 220000,
                'number_seat' => '45',
                'user_add_id' => null,
            ],
            [
                'route_id' => 6,
                'driver_id' => 3,
                'coach_id' => 6,
                'start_day' => '2018-10-26',
                'start_time' => '10:30:00',
                'is_active' => 2,
                'price' => 220000,
                'number_seat' => '45',
                'user_add_id' => null,
            ],
            [
                'route_id' => 6,
                'driver_id' => 4,
                'coach_id' => 6,
                'start_day' => '2018-10-26',
                'start_time' => '19:30:00',
                'is_active' => 1,
                'price' => 220000,
                'number_seat' => '45',
                'user_add_id' => null,
            ],
            [
                'route_id' => 6,
                'driver_id' => 4,
                'coach_id' => 6,
                'start_day' => '2018-10-26',
                'start_time' => '21:30:00',
                'is_active' => 2,
                'price' => 220000,
                'number_seat' => '45',
                'user_add_id' => null,
            ],
            [
                'route_id' => 6,
                'driver_id' => 4,
                'coach_id' => 6,
                'start_day' => '2018-10-26',
                'start_time' => '22:30:00',
                'is_active' => 1,
                'price' => 220000,
                'number_seat' => '45',
                'user_add_id' => null,
            ],
            [
                'route_id' => 6,
                'driver_id' => 4,
                'coach_id' => 6,
                'start_day' => '2018-10-26',
                'start_time' => '23:30:00',
                'is_active' => 2,
                'price' => 220000,
                'number_seat' => '45',
                'user_add_id' => null,
            ],
            [
                'route_id' => 6,
                'driver_id' => 3,
                'coach_id' => 7,
                'start_day' => '2018-10-30',
                'start_time' => '21:00:00',
                'is_active' => 1,
                'price' => 230000,
                'number_seat' => '45',
                'user_add_id' => null,
            ],
            [
                'route_id' => 6,
                'driver_id' => 4,
                'coach_id' => 7,
                'start_day' => '2018-10-30',
                'start_time' => '22:00:00',
                'is_active' => 2,
                'price' => 230000,
                'number_seat' => '45',
                'user_add_id' => null,
            ],
            [
                'route_id' => 6,
                'driver_id' => 4,
                'coach_id' => 7,
                'start_day' => '2018-11-10',
                'start_time' => '19:30:00',
                'is_active' => 1,
                'price' => 230000,
                'number_seat' => '45',
                'user_add_id' => null,
            ],
            [
                'route_id' => 6,
                'driver_id' => 4,
                'coach_id' => 7,
                'start_day' => '2018-11-10',
                'start_time' => '19:30:00',
                'is_active' => 2,
                'price' => 230000,
                'number_seat' => '45',
                'user_add_id' => null,
            ],
            [
                'route_id' => 6,
                'driver_id' => 4,
                'coach_id' => 7,
                'start_day' => '2019-01-10',
                'start_time' => '19:30:00',
                'is_active' => 3,
                'price' => 230000,
                'number_seat' => '45',
                'user_add_id' => null,
            ],
            [
                'route_id' => 6,
                'driver_id' => 1,
                'coach_id' => 7,
                'start_day' => '2018-11-10',
                'start_time' => '21:00:00',
                'is_active' => 1,
                'price' => 230000,
                'number_seat' => '45',
                'user_add_id' => null,
            ],
            [
                'route_id' => 6,
                'driver_id' => 3,
                'coach_id' => 7,
                'start_day' => '2018-11-10',
                'start_time' => '21:00:00',
                'is_active' => 2,
                'price' => 230000,
                'number_seat' => '45',
                'user_add_id' => null,
            ],
            [
                'route_id' => 6,
                'driver_id' => 4,
                'coach_id' => 7,
                'start_day' => '2018-11-10',
                'start_time' => '21:00:00',
                'is_active' => 1,
                'price' => 230000,
                'number_seat' => '45',
                'user_add_id' => null,
            ],
            [
                'route_id' => 6,
                'driver_id' => 4,
                'coach_id' => 7,
                'start_day' => '2018-11-10',
                'start_time' => '21:00:00',
                'is_active' => 2,
                'price' => 230000,
                'number_seat' => '45',
                'user_add_id' => null,
            ],
            // Add more data here
        ]);
    }
}
